FROM registry.redhat.io/ubi9/python-312

# Add application sources with correct permissions for OpenShift
USER 0
ADD app-src .
RUN chown -R 1001:0 ./
USER 1001

# Install the dependencies
RUN pip install -r requirements.txt

# Expose 8080
EXPOSE 8080

# Run the application
CMD ["python", "app.py"]